# Generated by Django 2.2 on 2022-12-15 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilelist',
            name='color',
            field=models.CharField(default='no', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mobilelist',
            name='ram',
            field=models.CharField(default='no', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mobilelist',
            name='storage',
            field=models.CharField(default='no', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mobilelist',
            name='price',
            field=models.IntegerField(),
        ),
    ]
