# Generated by Django 2.2 on 2022-12-23 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0002_auto_20221215_0503'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilelist',
            name='image',
            field=models.ImageField(default='s', upload_to='pics'),
            preserve_default=False,
        ),
    ]
